<img src="http://www.ronan-royet.fr/web_portal/img/footer.png"/>
<div class="main-footer">
<div class="footer-left">
    <h3><?getTranslation("links");?></h3>
    <ul>
        <li><a><?getTranslation("legal");?></a></li>
        <li><a><?getTranslation("agreement");?></a></li>
        <li><a><?getTranslation("questions");?></a></li>
    </ul>
</div>
<div class="footer-right">
    <h3><?getTranslation("follow");?></h3>
</div>
</div>
<div>&copy; International Digital Team</div>
