<nav id="nav">
    <ul>
        <li>
            <a href="#"><?getTranslation("nav1", $lang);?></a>
        </li>
        <li>
            <a href="#"><?getTranslation("nav2",$lang);?></a>
        </li>
        <li>
            <a href="#"><?getTranslation("nav3",$lang);?></a>
        </li>
        <li>
            <a href="#"><?getTranslation("nav4",$lang);?></a>
        </li>
    </ul>
</nav>

